<?php
/**
 * @file
 * Code for the Catalyst Admin feature.
 */

include_once 'catalyst_admin.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function catalyst_admin_entity_info_alter(&$entity_info) {
  catalyst_include('eck', 'admin');
  catalyst_admin_eck_entity_info_alter($entity_info);
}

/**
 * Implements hook_menu().
 */
function catalyst_admin_menu() {
  return array(
    'admin/catalyst' => array(
      'title' => 'Catalyst',
      'description' => 'Administer layouts, blocks, templates, and more.',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file path' => drupal_get_path('module', 'system'),
      'file' => 'system.admin.inc',
      'weight' => -10,
    ),
  );
}

/**
 * Implements hook_menu_alter().
 */
function catalyst_admin_menu_alter(&$menu_items) {
  catalyst_include('eck', 'admin');
  catalyst_admin_eck__entity_menu_alter($menu_items);
}

/**
 * Implements hook_module_implements_alter().
 */
function catalyst_admin_module_implements_alter(&$implementations, $hook) {
  // Ensure modifications and additions to the menu are done after
  // views_menu_alter() so menu items provided by views can be altered.
  if (in_array($hook, array('menu_alter', 'entity_info_alter'))) {
    $group = $implementations['catalyst_admin'];
    unset($implementations['catalyst_admin']);
    $implementations['catalyst_admin'] = $group;
  }
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Allow disabling tablesort from multiple value form widgets.
 *
 * @code
 *  $element['#nodrag'] = TRUE;
 * @endcode
 *
 * @see https://www.commercialprogression.com/post/how-remove-tabledrag-rearranging-multiple-value-field-widgets
 */
function catalyst_admin_theme_registry_alter(&$theme_registry) {
  $hook = 'field_multiple_value_form';
  if (isset($theme_registry[$hook])) {
    $module_path = catalyst_get_path('admin');
    $theme_registry[$hook] = array_merge($theme_registry[$hook], array(
      'type' => 'module',
      'theme path' => $module_path,
      'includes' => array($module_path . '/includes/theme.inc'),
      'function' => 'multi_widget_remove_tabledrag_theme_field_multiple_value_form',
    ));
  }
}

/**
 * Implements hook_form_alter().
 */
function catalyst_admin_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['field__admin_notes'])) {
    if (isset($form['#node'])) {
      $wrapper = entity_metadata_wrapper('node', $form['#node']);
    }
    elseif (isset($form['#entity_type'])) {
      $wrapper = entity_metadata_wrapper($form['#entity_type'], $form['#entity']);
    }
    $form['catalyst_form_help'] = array(
      '#type' => 'markup',
      '#markup' => '<p class="help catalyst-form-help">' . entity_valval($wrapper->field__admin_notes) . '</p>',
      '#weight' => -100000,
    );
  }

  // Alter views bulk operations forms
  if (strpos($form_id, 'views_form_catalyst_') === 0 && isset($form['output'])) {
    $form['#attached']['css'][] = catalyst_get_path('admin') . '/css/views.css';
    // After build callback in catalyst_admin/includes/uncommon.inc
    catalyst_form_load_include($form_state, 'uncommon', 'admin');
    $form['#after_build'][] = 'catalyst_admin_views_form_after_build';
  }
  elseif ($form_id == 'views_exposed_form' && strpos($form_state['view']->name, 'catalyst_') === 0) {
    $form['#attributes']['class'][] = 'container-inline';
    if (isset($form['secondary'])) {
      $form['secondary']['#attributes']['class'][] = 'container-inline';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a "Save & Edit" button to eck entity forms.
 */
function catalyst_admin_form_eck__entity__form_alter(&$form, &$form_state) {
  catalyst_form_load_include($form_state, 'save_edit', 'admin');
  catalyst_admin_save_edit_form_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a "Save & Edit" button to node forms.
 */
function catalyst_admin_form_node_form_alter(&$form, &$form_state) {
  // Allow the save_edit module to handle node forms when present
  if (!module_exists('save_edit')) {
    catalyst_form_load_include($form_state, 'save_edit', 'admin');
    catalyst_admin_save_edit_form_alter($form, $form_state);
  }
}


/**
 * Included in the module instead of includes/eck.inc as it will be called
 * on most every page.
 */
function catalyst_admin_eck_url_outbound($bundle, &$path, &$options, $original_path, $prefix = 'admin/structure') {
  $m = array();
  // Match catalyst/[bundle]/[entity id]
  if (preg_match('/catalyst\/' . $bundle . '\/([0-9]+)(.*)/i', $path, $m)) {
    // Alter the path according the provided arguments
    $path = $prefix . '/' . $bundle . '/' . $m[1] . $m[2];
  }
}

/**
 * Override for eck__entity_menu_access() which converts view access to edit
 * access in order to prevent non-admin access to viewing catalsyt entities
 * through the menu.
 */
function catalyst_admin_eck__entity_menu_access($action) {
  $args = func_get_args();
  if ($action == 'view') {
    $args[0] = 'edit';
  }
  return call_user_func_array('eck__entity_menu_access', $args);
}
