<?php
/**
 * @file
 * Code for the Catalyst Page feature.
 */

include_once 'catalyst_page.features.inc';

/**
 * Implements hook_theme().
 */
function catalyst_page_theme() {
  return array(
    'cpage_content' => array(
      'variables' => array(
        'template' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_block_placements().
 */
function catalyst_page_block_placements() {
  $node = menu_get_object();
  if (!empty($node->field_cpage_blocks)) {
    return $node->field_cpage_blocks[$node->language];
  }
}

function catalyst_page_form_cpage_node_form_alter(&$form, &$form_state) {
  $query = new EntityFieldQuery;
  $query->entityCondition('entity_type', 'catalyst')
    ->entityCondition('bundle', 'layout')
    ->addMetaData('account', user_load(1))
    ->addTag(__FUNCTION__);
  $result = $query->execute();
  if (isset($result['catalyst'])) {
    $callbacks = array(
      'onselect' => array(),
      'ondeselect' => array(),
    );
    $layouts = entity_load('catalyst', array_keys($result['catalyst']));
    foreach ($layouts AS $id => $_layout) {
      $layout = entity_metadata_wrapper('catalyst', $_layout);
      if ($onselect = $layout->field_layout_onselect->value()) {
        $callbacks['onselect'][$id] = $onselect;
      }
      if ($ondeselect = $layout->field_layout_ondeselect->value()) {
        $callbacks['ondeselect'][$id] = $ondeselect;
      }
    }
    $form['#attached']['js']['catalyst_page'] = drupal_get_path('module', 'catalyst_page') . '/catalyst_page_form.js';
    drupal_add_js(array(
      'pageLayoutOnChange' => array(
        'selector' => '#edit-field-cpage-layout-und',
        'callbacks' => $callbacks,
      )),
      'setting'
    );
  }
}

/**
 * Implements hook_node_view().
 */
function catalyst_page_node_view($node, $view_mode, $langcode) {
  $wrapper = entity_metadata_wrapper('node', $node);
  if ($wrapper->getBundle() == 'cpage' && $view_mode == 'full') {
    if ($layout = $wrapper->field_cpage_layout->value()) {
      catalyst_set_layout($layout);
    }
  }
}

/**
 * Implements hook_node_view_alter().
 */
function catalyst_page_node_view_alter(&$build) {
  if (isset($build['field_cpage_content'])) {
    if ($template = $build['field_cpage_content'][0]['#markup']) {
      $build['field_cpage_content'][0]['#markup'] = theme('cpage_content', array(
        'page' => entity_metadata_wrapper('node', $build['#node']),
        'template' => $template
      ));
    }
  }
}

function catalyst_page_preprocess_cpage_content(&$variables) {
  $node = $variables['page'];

  // Custom processing defined by the page
  if ($preprocess_php = $node->field_cpage_preprocess->value()['value']) {
    catalyst_eval($preprocess_php, $variables);
  }

  // Custom HTML head defined by the page
  if ($custom_html_head = $node->field_cpage_head->value()['value']) {
    drupal_add_html_head(
      array(
        '#type' => 'markup',
        '#markup' => $custom_html_head . "\n",
      ),
      'cpage_html_head'
    );
  }
}

function theme_cpage_content($variables) {
  module_load_include('inc', 'catalyst', 'includes/twig');
  return catalyst_twig_render($variables['template'], $variables, 'cpage_content');
}

/**
 * Implements hook_catalyst_export_groups().
 */
function catalyst_page_catalyst_export_groups() {
  return array(
    'cpage' => array(
      'title' => t('Pages'),
      'entity_type' => 'node',
      'bundle' => 'cpage',
      'weight' => -3,
      'feed_path' => 'admin/content/cpage/export.xml',
      'migration' => array(
        'class_name' => 'CatalystPageMigration',
      ),
    ),
  );
}

/**
 * Implements hook_catalyst_export_candidates().
 */
function catalyst_page_catalyst_export_candidates($type) {
  if ($type == 'cpage') {
    return entity_load('node', FALSE, array('type' => 'cpage'));
  }
}
