<?php
/**
 * @file
 * Code for the Catalyst Page feature.
 */

include_once 'catalyst_page.features.inc';

/**
 * Implements hook_theme().
 */
function catalyst_page_theme() {
  return array(
    'page_content' => array(
      'variables' => array(
        'template' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_block_placements().
 */
function catalyst_page_block_placements() {
  $node = menu_get_object();
  if (!empty($node->field__blockplacements__layfield)) {
    return $node->field__blockplacements__layfield[$node->language];
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function catalyst_page_entity_view_alter(&$build) {
  if ($build['#view_mode'] == 'template' && isset($build['field__body'])) {
    if ($template = $build['field__body'][0]['#markup']) {
      $build['field__body'][0]['#markup'] = theme('page_content', array(
        'template' => new CatalystEntityPage($build['#entity']),
      ));
    }
  }
}

function template_preprocess_page_content(&$variables) {
  $variables['title'] = drupal_get_title();
}

function catalyst_page_preprocess_page_content(&$variables) {
  $template = $variables['template'];

  if ($path = $template->getMenuPath()) {
    if ($pathvars = catalyst_menu_parse_path($path)) {
      $variables = array_merge($variables, $pathvars);
    }
  }

  // Custom processing defined by the page
  if ($preprocess_php = $template->getPreprocessPHP()) {
    catalyst_eval($preprocess_php, $variables, $pathvars);
  }

  // Custom HTML head defined by the page
  if ($custom_html_head = $template->getHTMLHead()) {
    drupal_add_html_head(
      array(
        '#type' => 'markup',
        '#markup' => $custom_html_head . "\n",
      ),
      'catalyst_page_html_head'
    );
  }
}

function theme_page_content($variables) {
  return $variables['template']->renderTemplate($variables);
}
