<?php

/**
 * @file
 * Code for the Catalyst Layout feature.
 */

include_once 'catalyst_layout.features.inc';

/**
 * Implements hook_entity_view().
 */
function catalyst_layout_entity_view($entity, $type, $view_mode, $langcode) {
  if (isset($entity->field__layout)) {
    $wrapper = entity_metadata_wrapper($type, $entity);
    if ($layout = $wrapper->field__layout->value()) {
      catalyst_set_layout($layout);
    }
  }
}

/**
 * Implements hook_menu().
 */
function catalyst_layout_menu() {
  return array(
    'admin/structure/layout/settings' => array(
      'title' => t('Settings'),
      'page callback' => 'catalyst_layout_admin_settings_page',
      'file path' => catalyst_get_path('layout') . '/includes',
      'file' => 'admin.inc',
      'type' => MENU_LOCAL_TASK,
      'access arguments' => array('do cool stuff'),
    ),
  );
}

/**
 * Implements hook_page_build().
 */
function catalyst_layout_page_build(&$page) {
  if (catalyst_theme_active() && !isset($page['#layout'])) {
    $page['#layout'] = catalyst_get_layout();
    $page['#doctype'] = catalyst_get_doctype();
  }
}

/**
 * Preprocess the layout.
 */
function catalyst_preprocess_layout(&$variables) {
  $layout = $variables['page']['#layout'];

  if ($add_html_head = $layout->getHTMLHead()) {
    drupal_add_html_head(
      array(
        '#type' => 'markup',
        '#markup' => $add_html_head,
      ),
      'layout_html_head'
    );
  }

  // Preprocessing defined by the layout
  if ($preprocess_php = $layout->getPreprocessPHP()) {
    catalyst_eval($preprocess_php, $variables);
  }
}

/**
 * Preprocess a doctype based on layout configuration.
 */
function catalyst_preprocess_doctype(&$variables) {
  $layout = $variables['page']['#layout'];
  // Customize the page title based on the layouts pattern
  if ($page_title_pattern = $layout->getPageTitlePattern()) {
    module_load_include('inc', 'catalyst', 'includes/twig');
    $variables['head_title'] = catalyst_twig_render(
      $page_title_pattern,
      $variables['head_title_array'],
      'layout_page_title_pattern'
    );
  }
}

/**
 * Helper shortcut function for fetching a layout template.
 */
function catalyst_layout_get_template(Entity $layout) {
  $build = eck__entity__view('catalyst', 'layout', $layout);
  return render($build);
}

function catalyst_layout_system_regions($layout = NULL) {
  if ($layout === NULL) {
    $layout = catalyst_get_layout();
  }
  return $layout->getRegions();
}

/**
 * Implements hook_block_placements().
 */
function catalyst_layout_block_placements() {
  return catalyst_get_layout()->getBlockPlacements();
}
