<?php
/**
 * @file
 * Code for the Catalyst Doctype feature.
 */

include_once 'catalyst_doctype.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function catalyst_doctype_form_eck__entity__form_alter(&$form, &$form_state, $form_id) {
  // Set the default value for the doctype content
  if (isset($form['field__body']) && catalyst_entity_is_new($form['#entity'])
    && $form['#entity']->type == 'doctype') {
    $lang = $form['field__body']['#language'];
    $form['field__body'][$lang][0]['#after_build'][] = 'field__body_set_default_value';
  }
}

/**
 * Implements hook_menu().
 */
function catalyst_doctype_menu() {
  $items['admin/catalyst/doctype/%eckentity/preview'] = array(
    'title' => 'Preview',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('catalyst_doctype_preview_form', 3),
    // Preview access with edit access
    'access callback' => 'eck__entity_menu_access',
    'access arguments' => array('edit', 'catalyst', 'doctype', 3),
    'type' => MENU_LOCAL_TASK,
    'file' => 'catalyst_doctype.pages.inc',
    'weight' => 9,
    'theme callback' => 'catalyst_doctype_custom_theme',
  );
  return $items;
}

/**
 * Implements hook_custom_theme().
 */
function catalyst_doctype_custom_theme() {
  if (preg_match('/admin\/catalyst\/doctype\/[0-9]+\/preview/i', request_path()) && count($_POST)) {
    return 'notheme';
  }
}

/**
 * Preprocess a doctype element.
 */
function catalyst_doctype_preprocess_doctype(&$variables) {
  $doctype = $variables['page']['#doctype'];

  if (!isset($variables['http_content_type'])) {
    $variables['http_content_type'] = $doctype->getContentType();
  }

  if (!isset($variables['http_charset'])) {
    $variables['http_charset'] = $doctype->getCharset();
  }

  // Custom Preprocessing defined by the doctype
  if ($preprocess_php = $doctype->getPreprocessPHP()) {
    catalyst_eval($preprocess_php, $variables);
  }
}

function catalyst_doctype_process_doctype(&$variables) {
  if (!isset($variables['http_content_type_header'])) {
    $variables['http_content_type_header'] = implode(';', array(
      $variables['http_content_type'],
      'charset=' . $variables['http_charset'],
    ));
  }
  drupal_add_http_header('Content-type', $variables['http_content_type_header']);
}

function catalyst_doctype_get_template(Entity $doctype) {
  $build = eck__entity__view('catalyst', 'doctype', $doctype);
  return render($build);
}

/**
 * After build callback for setting the doctype content default value.
 *
 * @see catalyst_doctype_form_alter().
 */
function field__body_set_default_value($element) {
  if (empty($element['#value'])) {
    $element['#value'] = field__body_default_value();
  }
  return $element;
}

function field__body_default_value() {
  return implode("\n", array(
    '<html>',
    '  <head>',
    '    {{ head }}',
    '    <title>{{ head_title }}</title>',
    '    {{ styles }}',
    '    {{ scripts }}',
    '  </head>',
    '  <body>',
    '    {{ page_top }}',
    '    {{ page }}',
    '    {{ page_bottom }}',
    '  </body>',
    '</html>',
  ));
}
