<?php
/**
 * @file
 * Code for the Catalyst Navbar feature.
 */

include_once 'catalyst_navbar.features.inc';

/**
 * @file
 * Integrates the navbar and responsive_preview modules with Catalyst.
 *
 * @todo
 *
 * Presently, Catalyst is intented to provide a clean workspace where javascript
 * and css is managed through the system. Navbar requires jQuery and needs
 * to be self contained so as to avoid collisions with Catalyst.
 */

/**
 * @file
 */

function catalyst_navbar_library_alter(&$libraries, $module) {
  if (catalyst_theme_active() && user_access('access navbar') && in_array($module, array('navbar','responsive_preview'))) {
    $layout = catalyst_get_layout();
    $add_css = !in_array(CSS_SYSTEM, $layout->getDrupalCSSOptions());
    $add_js = !in_array(JS_LIBRARY, $layout->getDrupalJSOptions());

    if (!$add_css && !$add_js) {
      return;
    }

    if ($module == 'navbar') {
      if ($add_css) {
        drupal_add_css('profiles/catalyst/css/clearfix.css', array('group' => -201));
      }
      if ($add_js) {
        drupal_add_js('profiles/catalyst/js/jquery-1.9.0.min.js', array('group' => -302));
        drupal_add_js('profiles/catalyst/js/jquery.once-1.2.6.min.js', array('group' => -301));
        drupal_add_js('misc/drupal.js', array('group' => -201));
      }
    }

    foreach (array_keys($libraries) AS $i) {
      if ($add_js && isset($libraries[$i]['js'])) {
        catalyst_alter_library($libraries[$i]['js']);
      }
      if ($add_css && isset($libraries[$i]['css'])) {
        catalyst_alter_library($libraries[$i]['css']);
      }
    }
  }
}

function catalyst_alter_library(&$library) {
  $return = array();
  foreach ($library AS $key => $value) {
    $override = array(
      'group' => CATALYST_JS_LIBRARY,
    );
    if (is_array($value)) {
      $return[$key] = array_merge($value, $override);
    }
    else {
      $return[$value] = $override;
    }
  }
  $library = $return;
}

function catalyst_navbar_navbar() {
  $items['fg_admin'] = array(
    '#attached' => array(
      'css' => array(drupal_get_path('module', 'catalyst_navbar') . '/css/navbar.css'),
    ),

  );
  return $items;
}