<?php

/**
 * @file
 */

function catalyst_navbar_library_alter(&$libraries, $module) {
  global $theme;
  if ($theme == 'notheme' && user_access('access navbar') && in_array($module, array('navbar','responsive_preview'))) {
    if ($module == 'navbar') {
      drupal_add_css('profiles/catalyst/css/clearfix.css', array('group' => -201));
      //drupal_add_css('modules/system/system.base.css', array('group' => -201));
      //drupal_add_js('misc/jquery.js', array('group' => -302));
      drupal_add_js('profiles/catalyst/js/jquery-1.9.0.min.js', array('group' => -302));
      //drupal_add_js('profiles/catalyst/js/jquery-1.11.3.min.js', array('group' => -201));
      drupal_add_js('profiles/catalyst/js/jquery.once-1.2.6.min.js', array('group' => -301));
      drupal_add_js('misc/drupal.js', array('group' => -201));
    }

    foreach (array_keys($libraries) AS $i) {
      if (isset($libraries[$i]['js'])) {
        catalyst_alter_library($libraries[$i]['js']);
      }
      if (isset($libraries[$i]['css'])) {
        catalyst_alter_library($libraries[$i]['css']);
      }
    }
  }
}

function catalyst_alter_library(&$library) {
  $return = array();
  foreach ($library AS $key => $value) {
    $override = array(
      'group' => -101,
    );
    if (is_array($value)) {
      $return[$key] = array_merge($value, $override);
    }
    else {
      $return[$value] = $override;
    }
  }
  $library = $return;
}
function catalyst_alter_library_css(&$library) {

}
